//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowersShopApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bouquet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bouquet()
        {
            this.BouquetFlower = new HashSet<BouquetFlower>();
            this.OrderHistory = new HashSet<OrderHistory>();
        }
    
        public int Id { get; set; }
        public byte[] Picture { get; set; }
        public string Name { get; set; }
        public int PackageId { get; set; }
        public double Cost { get; set; }
    
        public virtual Package Package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BouquetFlower> BouquetFlower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHistory> OrderHistory { get; set; }
    }
}
